### ISSUE TITLE
Using VirusTotal's official open source command line tool

### ISSUE THREAD

**Issue by lzw-723** [nim-lang/virus_checker#3]
[VirusTotal CLI](https://github.com/VirusTotal/vt-cli) A tool designed for people who use VirusTotal via the command line.
It looks easy to use in GitHub Actions. This is just a simple and straightforward way to implement an additional tool that calls the VirusTotal api, which can have a richer applicability. (¬‿¬)

**Comment by ringabout** [comment]
related https://github.com/nim-lang/Nim/issues/17820

**Comment by ringabout** [comment]
https://github.com/marketplace/actions/virustotal-github-action can be used, I can register VT_API_KEY in the GitHub settings if someone is interested.
